#' Identify the meta-program of each cell lineage, and process the meta-programs (MPs) with a focus on quality control and annotation.
#' @param Singcell_Seurat_path Path of integrated single cell expression matrix
#' @param Metacell_Seurat_path Path of integrated metacells
#' @param MPs_genelist_path Path of gene list of MetaPrograms generated by NMF
#' @param Cell_linega Specific lineage used for analysis
#' @author Ya Han

library(MAESTRO)
library(Seurat)
library(GSVA)

args <- commandArgs(trailingOnly = TRUE)
Singcell_Seurat_path<-args[1]
Metacell_Seurat_path<-args[2]
MPs_genelist_path<-args[3]
Cell_linega<-agrs[4]

################Single cell######################
Myeloid_invo_dataset_tumor=list.files(Singcell_Seurat_path)
#including all MPs gene list after quality control
MPs_genelist=readRDS(MPs_genelist_path)#including all MPs gene list without quality control

setwd(Singcell_Seurat_path)
batch_calculate_MPs_score_singlecell_level<-function(temp_dataset){
  temp_filelist=list.files(temp_dataset[2],full.names = TRUE)
  Myeloid_seu=readRDS(temp_filelist[grep("_res.rds",temp_filelist)])
  Myeloid_seu=Myeloid_seu$RNA
  myofibro_cells=rownames(Myeloid_seu@meta.data)[which(Myeloid_seu@meta.data$assign.curated %in% Cell_linega)]
  Myeloid_seu=subset(Myeloid_seu,cells=myofibro_cells)
  DefaultAssay(Myeloid_seu)<-"RNA"
  expmat=GetAssayData(Myeloid_seu)
  expmat=as.matrix(expmat)
  
  Myeloid_Minicluster_MPs_score=gsva(expmat,MPs_genelist,method="ssgsea")
  saveRDS(Myeloid_Minicluster_MPs_score,file=paste0("./",temp_dataset[1],"_sclevel_Highqulaty_MPs_GSVA_score.rds"))
}
result=apply(as.matrix(Myeloid_invo_dataset_tumor),1,batch_calculate_MPs_score_singlecell_level)



###################metacell level####################

Myeloid_seu=readRDS(Metacell_Seurat_path)
Myeloid_seu@meta.data$curated_anno=as.vector(unlist(Myeloid_meta$curated_anno[match(rownames(Myeloid_seu@meta.data),rownames(Myeloid_meta))]))
#including all MPs gene list after quality control
MPs_genelist=readRDS(MPs_genelist_path)

DefaultAssay(Myeloid_seu)<-"RNA"
expmat=GetAssayData(Myeloid_seu)
expmat=as.matrix(expmat)

Myeloid_Minicluster_MPs_score=gsva(expmat,MPs_genelist,method="ssgsea")


